/*

This file is generated by lfsr-generator 1.0.2.
Copyright (C) 2007  Wakabayashi Masaki

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

unsigned int shift_lfsr(unsigned int v)
{
	/*
		config          : fibonacci
		length          : 16
		taps            : (16, 15, 14, 5)
		shift-amounts   : (1)
		shift-direction : left
	*/
	enum {
		length         = 16,
		tap_0          = 16,
		tap_1          = 15,
		tap_2          = 14,
		tap_3          =  5,
		shift_amount_0 =  1
	};
	typedef unsigned int T;
	const T zero = (T)(0);
	v = (
		(
			v << shift_amount_0
		) | (
			(
				(v >> (tap_0 - shift_amount_0)) ^
				(v >> (tap_1 - shift_amount_0)) ^
				(v >> (tap_2 - shift_amount_0)) ^
				(v >> (tap_3 - shift_amount_0))
			) & (
				~(~zero << shift_amount_0)
			)
		)
	);
	return v;
}

#ifdef __cplusplus
} /* end of extern "C" */
#endif /* __cplusplus */
